//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] GrammarParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] GrammarParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] GrammarParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] GrammarParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalDeclaration([NotNull] GrammarParser.GlobalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalDeclaration([NotNull] GrammarParser.GlobalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] GrammarParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] GrammarParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] GrammarParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] GrammarParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] GrammarParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] GrammarParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] GrammarParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] GrammarParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] GrammarParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] GrammarParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] GrammarParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] GrammarParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] GrammarParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] GrammarParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] GrammarParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] GrammarParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallStatement([NotNull] GrammarParser.CallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallStatement([NotNull] GrammarParser.CallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] GrammarParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] GrammarParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivMod</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivMod([NotNull] GrammarParser.MulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivMod</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivMod([NotNull] GrammarParser.MulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSub([NotNull] GrammarParser.AddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSub([NotNull] GrammarParser.AddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAnd([NotNull] GrammarParser.LogicalAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAnd</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAnd([NotNull] GrammarParser.LogicalAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelational([NotNull] GrammarParser.RelationalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelational([NotNull] GrammarParser.RelationalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] GrammarParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] GrammarParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Unary</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary([NotNull] GrammarParser.UnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Unary</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary([NotNull] GrammarParser.UnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOr([NotNull] GrammarParser.LogicalOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalOr</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOr([NotNull] GrammarParser.LogicalOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryOperator</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] GrammarParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryOperator</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] GrammarParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreIncrement</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreIncrement([NotNull] GrammarParser.PreIncrementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreIncrement</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreIncrement([NotNull] GrammarParser.PreIncrementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreDecrement</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreDecrement([NotNull] GrammarParser.PreDecrementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreDecrement</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreDecrement([NotNull] GrammarParser.PreDecrementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostIncrementDecrement</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostIncrementDecrement([NotNull] GrammarParser.PostIncrementDecrementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostIncrementDecrement</c>
	/// labeled alternative in <see cref="GrammarParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostIncrementDecrement([NotNull] GrammarParser.PostIncrementDecrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] GrammarParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] GrammarParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialValue([NotNull] GrammarParser.InitialValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialValue([NotNull] GrammarParser.InitialValueContext context);
}
